version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.3
    restart: always
    container_name: quota_elasticsearch1
    environment:
      - node.name=quota
      - cluster.name=quota-cluster
      - http.host=0.0.0.0
      - http.port=9200
      - transport.publish_host=127.0.0.1
      - http.publish_host=127.0.0.1
      - transport.tcp.port=9300
      - transport.tcp.connect_timeout=10s
      - discovery.zen.minimum_master_nodes=1
      - discovery.type=single-node
      - http.cors.enabled=true
      - node.data=true
      - node.master=true
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.ml.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300

#
#volumes:
#  stubbornjava_esdata:
#    driver: local
